node {
    git url: 'https://github.com/TamirHadad/pipelineDemo.git'
    def filePathPrefix = 'placeholder-example/'

    // In case you want to use some Artifactory which is not pre-configure,
    // use Artifactory.newServer(String url, String userName, String password)
    def server = Artifactory.newServer ART_URL, ART_USER, ART_PASSWORD
    def uploadJson = readFile "${filePathPrefix}upload.json"
    withEnv(['SayMyName=heisenberg']) {
        // the buildInfo will contains the environment variables in this scope
        buildInfo1 = server.upload uploadJson

  }
    def resolveJson = readFile "${filePathPrefix}download.json"
    def buildInfo2 = server.download resolveJson
    // merge the buildInfo data
    buildInfo1.append buildInfo2
    // publish buildInfo to artifactory
    server.publishBuildInfo buildInfo1
}
